- hosts: all

  tasks:

    - name: Install required packages
      apt: pkg=apache2 state=installed update_cache=yes

    - name: Upload static site
      copy: src=_build/html dest=/var/www owner=www-data group=www-data mode=644

    - name: Restart Apache
      service: name=apache2 state=restarted

